import type { useTaskIndexThreadState } from './useTaskIndexThreadState';

type TaskIndexThreadState = ReturnType<typeof useTaskIndexThreadState>;

export function taskIndexThreadBindings(thread: TaskIndexThreadState) {
    return {
        cancelThreadEdit: thread.cancelThreadEdit,
        commentsScrollRef: thread.commentsScrollRef,
        contextMenuMessageId: thread.contextMenuMessageId,
        contextMenuSelectionText: thread.contextMenuSelectionText,
        copyEntireMessage: thread.copyEntireMessage,
        copySelectedMessage: thread.copySelectedMessage,
        deleteThreadMessage: thread.deleteThreadMessage,
        handleReplyReferenceClick: thread.handleReplyReferenceClick,
        handleMentionQuery: thread.handleMentionQuery,
        handleSlashCommand: thread.handleSlashCommand,
        handleThreadSend: thread.handleThreadSend,
        lightboxAlt: thread.lightboxAlt,
        lightboxOpen: thread.lightboxOpen,
        lightboxSrc: thread.lightboxSrc,
        onCommentContextMenuOpen: thread.onCommentContextMenuOpen,
        onCommentsMediaLoadCapture: thread.onCommentsMediaLoadCapture,
        onGlobalClickCapture: thread.onGlobalClickCapture,
        onGlobalDblClickCapture: thread.onGlobalDblClickCapture,
        onGlobalKeyDownCapture: thread.onGlobalKeyDownCapture,
        onMessageDblClick: thread.onMessageDblClick,
        onMessageCopy: thread.onMessageCopy,
        onMessageTouchEnd: thread.onMessageTouchEnd,
        onRichContentClick: thread.onRichContentClick,
        scrollCommentsToBottomSoon: thread.scrollCommentsToBottomSoon,
        shouldShowCopySelection: thread.shouldShowCopySelection,
        startReplyToMessage: thread.startReplyToMessage,
        startThreadEdit: thread.startThreadEdit,
        setThreadAudience: thread.setThreadAudience,
        threadAudience: thread.threadAudience,
        threadAudienceError: thread.threadAudienceError,
        threadAiContext: thread.threadAiContext,
        threadComposerHtml: thread.threadComposerHtml,
        threadComposerRef: thread.threadComposerRef,
        threadComposerUploading: thread.threadComposerUploading,
        threadEditError: thread.threadEditError,
        threadEditSaving: thread.threadEditSaving,
        threadEditingId: thread.threadEditingId,
        threadError: thread.threadError,
        threadLoading: thread.threadLoading,
        threadMentionCandidates: thread.threadMentionCandidates,
        threadMentionError: thread.threadMentionError,
        threadMentionLoading: thread.threadMentionLoading,
        threadMessages: thread.threadMessages,
        threadSending: thread.threadSending,
        threadTempIdentifier: thread.threadTempIdentifier,
    };
}
